name = "Dartis-Craft - Kakusei 2 - Galaxy Gates"
author = "Dartis-Craft"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34acd47954b4466cfa5e7c2353990d01ea300b39e4f4f94c3ca21ca6f3df135d"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
